name: generate animation

on:
  schedule:
    - cron: "0 */22 * * *" 
  workflow_dispatch:
  push:
    branches:
    - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: patbil
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: push snake.svg to the snake branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}